Simulartor hang oom
NVIDIA/NVFlare pull request #1159
Opened 2022-11-18 20:03 UTC by yhwen

2022-11-18 21:06 UTC, yanchengnv requested changes

2022-11-18 21:27 UTC, yhwen commented on nvflare/private/fed/client/fed_client_base.py
> +    def quite_remote(self, project_name, fl_ctx: FLContext):
a type. Fixed.

2022-11-18 21:27 UTC, yhwen commented on nvflare/private/fed/client/fed_client_base.py
> +            return pool.map(partial(self.quite_remote, fl_ctx=fl_ctx), tuple(self.servers))
Fixed.

2022-11-22 14:10 UTC, yhwen commented
/nuild

2022-11-22 14:11 UTC, yhwen commented
/build

2022-11-29 14:57 UTC, yhwen commented on nvflare/private/fed/client/fed_client_base.py
> +            return pool.map(partial(self.quit_remote, fl_ctx=fl_ctx), tuple(self.servers))
One FL server can support multiple FL projects at the same time. It uses the project_name to distinguish which service. This is consistent with all the other service functions.

2022-12-07 15:38 UTC, merged