PSI initial PR
NVIDIA/NVFlare pull request #1207
Opened 2023-01-03 22:33 UTC by chesterxgchen

**PSI Initial PR**
are under the following assumptions 
1) PR is only works in Linux env. it doesn't work for Mac at the moment
2) PR will has failure when there is certain ratio of items size of PSI server and client ( underline openmined psi issue) 

The PSI is designed to have the following components and Alogrithms. 
**Algorithms:** 
  * Pair-wise Client interaction (via server) are used leverage 2-party client PSI
  * Both Forward pass and Backpass are leverage parallel executions (see design for details)

**System design:** 

**Client Side:** 

PSIExecutor –  FLARE Executor for PSI
ClientExecutor – FLARE Interface to handle real client execution ( invoke method ClientExectuor.client_exec()) 
DhPSIExecutor – an Implementation of ClientExector Interface for openmined PSI
PSI – a user facing FLComponent, PSIExecutor will need to delegate to user to implement. 
PsiClient –  wrapper for the client part of two-party PSI algorithm
PsiServer – wrapper for the server part of the two-party PSI algorithm

**Server side:** 
   PSIController – FLARE Controller for PSI 
   PSIWorkflow – PSI Workflow, one for each PSI Algorithm

Although one can configure the PSI server side operation via PSIController and PSIWorkflow, we added 
```
class DhPSIController(PSIController)
```
to simply the configuration 

**Example,** 
We added an basic example, other examples might be added later

**Client-Server Interaction sequence diagram**
https://github.com/chesterxgchen/NVFlare/blob/psi2/nvflare/app_common/psi/README.md

2023-01-04 18:31 UTC, holgerroth commented on nvflare/app_common/app_constant.py
> +    PSI_TASK_KEY = "PSI_TASK_KEY"
We might not need the `PSI_` prefix as the class name already specifies "PSI".

2023-01-04 19:01 UTC, holgerroth commented on nvflare/app_common/psi/psi_workflow_spec.py
> +    def pre_workflow(self, abort_signal: Signal) -> bool:
Consider calling these methods "preprocess," "run," and "postprocess".

2023-01-13 18:56 UTC, IsaacYangSLA requested changes
LGTM.  However, when we build the wheel, the build process ignores any folder that has no __init__.py file.  I believe some of the new folders in this PR do not have that file.  Can you help add them?

2023-01-13 19:27 UTC, IsaacYangSLA approved these changes
LGTM.

2023-01-13 19:38 UTC, merged