Quick start [skip ci]
NVIDIA/NVFlare pull request #1385
Opened 2023-02-17 18:32 UTC by chesterxgchen

Fixes # .

### Description
This is an tempt to add really short  guide for user to quickly running FLARE without much explanation. 
User can continue to read get start for more details. 

changes made
1) quickstart.rst 
2) README.md  directly add quick start in readme, but not include the production mode section
3) Draft the initial feature release section

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-02-21 23:57 UTC, YuanTingHsieh commented on docs/quickstart.rst
> +**Quick start with Production Mode**
contents are good, just this question, do we want to include this "Production Mode"(secure mode) in quick start? 

@kkersten @nvkevlu @holgerroth what do you guys think?

2023-02-22 01:27 UTC, holgerroth commented on docs/quickstart.rst
> +**Quick start with Production Mode**
I agree. "Quick start with Production Mode" should probably be its own page.

2023-02-22 01:32 UTC, holgerroth requested changes

2023-02-22 01:32 UTC, holgerroth commented on README.md
> +
I don't think this should be before "NVIDIA Federated Learning Application Runtime Environment"

2023-02-22 01:32 UTC, holgerroth commented on README.md
> +* **Quick Start with Simulator**
Why are this one and "Quick start with POC mode" bullet points? I think they should be sections with #### as well.

2023-02-22 01:32 UTC, holgerroth commented on docs/quickstart.rst
> +**Quick start with Production Mode**
Sorry, it's fine in the rst file, I think but in the root readme md file, it should link to the docs maybe for the production mode?

2023-02-22 02:28 UTC, holgerroth commented on docs/quickstart.rst
> +**Quick start with Production Mode**
@chesterxgchen , I think it would be great if we could make these "advanced" sections collapsible https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

2023-02-22 03:11 UTC, kkersten commented on README.md
> +$ mkdir -p /tmp/nvflare
Do we want to run this in `/tmp/nvflare`?  or create a per-job subdirectory, like `/tmp/nvflare/hello-numpy-run`?  or possibly even run in a local temporary subdir.  I have occasionally had collisions or permission issues when running in /tmp/nvflare - accidentally overwriting output I wanted to save to review, or hitting ownership issues when running with multiple users.

2023-02-22 03:13 UTC, kkersten commented on docs/quickstart.rst
> +**Quick start with Production Mode**
+1 to making advanced sections collapsible.  If that's not possible, I'd vote for moving Quick Start in Production Mode its own page.

2023-02-22 16:46 UTC, holgerroth commented on README.md
> +* **Quick Start with Simulator**
Yes, let's just use "####" for both and remove "Quick start with CLI".

Btw, I think `mkdir -p /tmp/nvflare` is not required the folder is created by the simulator.

2023-02-22 18:38 UTC, holgerroth requested changes
some minor suggestions @chesterxgchen

2023-02-22 18:38 UTC, holgerroth commented on docs/quickstart.rst
> +**Quick start with CLI**
Should this also be removed to be consistent with the markdown readme?

2023-02-22 18:38 UTC, holgerroth commented on docs/quickstart.rst
> +* **Quick Start with Simulator**
And turn these into Section titles rather than bullet points.

2023-02-22 18:59 UTC, holgerroth commented on docs/quickstart.rst
> +  $ python3 -m pip install -r examples/hello-world/hello-numpy-sag/requirements.txt
Do we need this line? There will be no output from pip I think with an empty requirements.txt or will it even run? hello-numpy-sag doesn't seem to have any additional requirements.

2023-02-22 20:20 UTC, holgerroth approved these changes
Looks good!

2023-02-22 20:33 UTC, merged