Move virtual env of all examples to main folder
NVIDIA/NVFlare pull request #1411
Opened 2023-02-24 02:58 UTC by ZiyueXu77

Fixes # .

### Description

Move the repeated virtual env setup section in all example's readme to the main readme, standardize to two requirements files within each example folder

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-02-24 05:00 UTC, YuanTingHsieh requested changes
Thanks for the effort, please don't change cifar10 example in this PR.
I will submit a PR that fix this and move cifar10

2023-02-24 20:44 UTC, ZiyueXu77 commented on examples/virtualenv/set_env.sh
> +export projectname='venv_nvflare_example'
sure

2023-02-24 20:45 UTC, ZiyueXu77 commented
> 

sure, reversed changes to cifar

2023-02-24 20:47 UTC, ZiyueXu77 commented on examples/advanced/brats18/README.md
>  bash testing_models_3d.sh
thanks for the suggestion! we can apply a general fix in another PR

2023-02-24 21:52 UTC, YuanTingHsieh approved these changes
Thanks, LGTM for this one.
We can do some other re-factors later.

2023-02-24 21:53 UTC, ZiyueXu77 commented
/build

2023-02-24 22:24 UTC, YuanTingHsieh commented
/build

2023-02-25 00:40 UTC, YuanTingHsieh commented
/build

2023-02-25 15:57 UTC, ZiyueXu77 commented
/build

2023-02-25 22:55 UTC, merged