Improve POC shutdown
NVIDIA/NVFlare pull request #1438
Opened 2023-02-28 21:45 UTC by chesterxgchen

Fixes # .

### Description
The poc shutdown currently implemented as by touch shutdown.fl. This will trigger the FL server and FL Clients to kill the job process shutdown themselves. 

Although this works,  since its killing the child job process directly, user might see error messages such leak semaphore and other internal messages. 
This PR tried to avoid that by using Admin API to shutdown properly. The new steps are 
1) Instantiate the Flare API (session)
2) list the jobs and find the active running jobs 
3) if there are active running jobs, abort the jobs first, ignore the invalid job Ids 
4) calling session.api.do_command to shutdown -all  to trigger system shutdown (Client + Server) 
5) close the connection (locks) from Admin to Server
6) still using  shutdown.fl to trigger shutdown as double check (although seems unnecessary) 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-02-28 22:25 UTC, yanchengnv requested changes
Please change to use the new flare api.

2023-02-28 22:25 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +        admin_api = _get_admin_api(poc_workspace)
I think we should change to use the new flare_api. It should be much easier.

2023-02-28 23:33 UTC, yhwen commented on nvflare/lighter/poc_commands.py
> +    time.sleep(3)
Should use login_with_poc() to login, instead of sleep.

2023-03-01 17:59 UTC, YuanTingHsieh requested changes

2023-03-01 17:59 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +    admin_api = FLAdminAPI(
If not using this method, we should remove it

2023-03-01 17:59 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +from nvflare.fuel.hci.client.fl_admin_api import FLAdminAPI
Some using new api don't need the old one

2023-03-01 19:33 UTC, yanchengnv requested changes
Please change to use new_insecure_session(); revert changes to flare_api for new_secure_session(); remove unused methods/functions.

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/fuel/flare_api/flare_api.py
> +                       secure_mode: bool = True) -> Session:
Why do we need secure_mode here? This method is intended for creating a secure session.
If you want insecure session, use new_insecure_session() method.

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +        sess = new_secure_session("admin", admin_dir, secure_mode=False)
Change to: sess = new_insecure_session().

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +def _get_admin_api(poc_workspace: str) -> FLAdminAPI:
Not needed

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +def _get_overseer_agent(admin_config):
Not needed.

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +def _get_admin_config(poc_workspace):
Not needed

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +def _get_transfer_dirs(admin_config, poc_workspace):
Not needed

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +def _load_admin_config(admin_config_path) -> dict:
Not needed

2023-03-01 19:33 UTC, yanchengnv commented on nvflare/lighter/poc_commands.py
> +from nvflare.fuel.flare_api.flare_api import new_secure_session
Change to import new_insecure_session

2023-03-01 21:32 UTC, yanchengnv approved these changes
LGTM

2023-03-01 22:16 UTC, YuanTingHsieh commented
Please fix unit test errors thanks

2023-03-02 00:16 UTC, YuanTingHsieh approved these changes

2023-03-02 01:48 UTC, YuanTingHsieh commented
/build

2023-03-02 02:07 UTC, merged