Make consistent the error message for shutdown_system without auth
NVIDIA/NVFlare pull request #1614
Opened 2023-03-30 15:00 UTC by nvkevlu

There were inconsistencies in the error messages for shutdown_system depending on whether the admin was part of the overseer's org. With this change, the error messages should be consistent.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-03-30 16:06 UTC, yanchengnv requested changes
See my comments.

2023-03-30 18:30 UTC, nvkevlu commented
/build

2023-03-30 19:21 UTC, nvkevlu commented
/build

2023-03-30 20:24 UTC, yanchengnv commented on nvflare/ha/ha_admin_cmds.py
> +        self.overseer_agent = overseer_agent  # we should not need self.overseer_agent anymore
Why not? Since this is provided, we should use it in all methods, instead of getting it from service_finder.

2023-03-30 20:28 UTC, YuanTingHsieh commented on nvflare/ha/ha_admin_cmds.py
>          self.logger = logging.getLogger(self.__class__.__name__)
just a note, can be done in another PR later, these 2 things are not used we can remove them both.

2023-03-30 20:28 UTC, YuanTingHsieh commented on nvflare/ha/ha_admin_cmds.py
> +    def list_sp(self, args, ctx: CommandContext):
Just a note, can be done in another PR later.
These methods don't need to be instance method as they are not using "self"

2023-03-30 23:06 UTC, nvkevlu commented on nvflare/private/fed/server/cmd_utils.py
> +        if args[0] == AdminCommandNames.ADMIN_CHECK_STATUS and len(args) == 1:
for AdminCommandNames.ADMIN_CHECK_STATUS, authz_func=self.must_be_project_admin in training_cmds.py

2023-03-31 01:39 UTC, yanchengnv commented on nvflare/private/fed/server/cmd_utils.py
> +        if args[0] == AdminCommandNames.ADMIN_CHECK_STATUS and len(args) == 1:
Oh, I see we need to extend the args with "server" in it so the handler will see "check_status server". Nice detail!

2023-03-31 12:24 UTC, merged