Update admin client command line interface to based on AdminAPI
NVIDIA/NVFlare pull request #162
Opened 2022-01-28 00:37 UTC by YuanTingHsieh

Fix #155

2022-02-02 17:59 UTC, nvkevlu commented
Thank you @YuanTingHsieh, the changes look very good for the most part. I wanted to test fully to make sure everything still works, and there is an issue with previous fl_admin.py scripts in an SSL configuration not working because poc is always set to True.

2022-02-04 16:40 UTC, nvkevlu requested changes

2022-02-04 23:53 UTC, YuanTingHsieh commented on nvflare/fuel/hci/client/cli.py
> +            poc=True,
thanks, fixed.

2022-02-07 17:18 UTC, nvkevlu approved these changes
Thanks, this now works with all the setups I tried.

2022-02-07 22:33 UTC, yanchengnv approved these changes

2022-02-07 23:48 UTC, YuanTingHsieh commented on nvflare/fuel/hci/client/cli.py
> +        credential_type: Union[str, CredentialType] = CredentialType.PASSWORD,
good point, let me submit a small fix PR follow this up.

2022-02-07 23:48 UTC, merged

2022-02-07 23:58 UTC, YuanTingHsieh commented on nvflare/fuel/hci/client/cli.py
> +        credential_type: Union[str, CredentialType] = CredentialType.PASSWORD,
fixed in #188