Add GPT-2 model
NVIDIA/NVFlare pull request #1626
Opened 2023-03-31 15:15 UTC by ZiyueXu77

Fixes # .

### Description

Add GPT-2 model to the NLP example, corrections to the data sequence and label alignment function, update readme 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [x] Documentation updated.

2023-03-31 17:06 UTC, ZiyueXu77 commented on examples/advanced/sklearn-kmeans/sklearn_kmeans_iris.ipynb
>     },
ah thanks! residual from yesterday, I should have used a different folder for that.

2023-03-31 22:34 UTC, holgerroth approved these changes
Looks good.

2023-03-31 22:37 UTC, ZiyueXu77 commented
/build

2023-03-31 23:23 UTC, ZiyueXu77 commented
/build

2023-04-03 19:59 UTC, holgerroth requested changes
Change computing of model weights to `model_diff[name] = np.subtract(local_weights[name].cpu().numpy(), global_weights[name], dtype=np.float32)` to ensure the model is runnable on more systems.

2023-04-03 22:56 UTC, ZiyueXu77 commented
> Change computing of model weights to `model_diff[name] = np.subtract(local_weights[name].cpu().numpy(), global_weights[name], dtype=np.float32)` to ensure the model is runnable on more systems.

was planning to merge this first then update all in a single PR, anyway, updated this one first

2023-04-03 22:59 UTC, holgerroth approved these changes

2023-04-03 23:27 UTC, ZiyueXu77 commented
/build

2023-04-04 00:01 UTC, merged