Clean up AdminAPI and rename AdminClient to AdminCLI
NVIDIA/NVFlare pull request #1678
Opened 2023-04-10 23:41 UTC by YuanTingHsieh

### Description

- Rename `AdminClient` to `AdminCLI` to better reflects the functionalities
- Remove login/login_with_poc function in `FLAdminAPI` as it conflicts with auto_login
- Our `AdminAPI` now required `ServiceFinder` and it can't be None

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-04-13 08:01 UTC, YuanTingHsieh commented
/build

2023-04-13 18:43 UTC, yanchengnv commented
I am not sure I understand the need of this PR. Let's discuss this first.

2023-04-14 11:37 UTC, nvkevlu commented
Looks very good to me. My only suggestion is to add "in seconds" to the auto_login_timeout and auto_login_interval descriptions so it is clearer to the user what unit it is.

2023-04-14 18:52 UTC, YuanTingHsieh commented
/build

2023-04-14 21:12 UTC, YuanTingHsieh commented
/build

2023-04-14 21:15 UTC, YuanTingHsieh commented
/build

2023-04-14 21:16 UTC, yanchengnv requested changes
Please improve the API's auto login control args.

2023-04-14 21:16 UTC, yanchengnv commented on nvflare/fuel/hci/client/api.py
> +            auto_login_interval: how often to try to auto-login, unit is second
I don't think we need to allow auto_login_interval to be configurable by the user to prevent stressing out the system (e.g. it's set to 0.0001). It is okay to set to 1.0 sec (or even larger).
Instead of auto_login_timeout, we could do auto_login_max_tries=5
Also need to validate it: must be > 0, and < a preset max (e.g. 300)

2023-04-14 21:16 UTC, yanchengnv commented on nvflare/fuel/hci/client/api.py
> +            if time.time() - start_time >= self.auto_login_timeout:
Change to test max number of tries.

2023-04-14 21:47 UTC, YuanTingHsieh commented on nvflare/fuel/hci/client/api.py
> +            auto_login_interval: how often to try to auto-login, unit is second
thanks, fixed as suggested

2023-04-14 21:47 UTC, YuanTingHsieh commented on nvflare/fuel/hci/client/api.py
> +            if time.time() - start_time >= self.auto_login_timeout:
thanks, fixed as suggested

2023-04-14 21:47 UTC, YuanTingHsieh commented
/build

2023-04-14 22:09 UTC, yanchengnv approved these changes
LGTM. Please make sure that all places that use FLAdminAPI is updated since you changed the position of overseer_agent.

2023-04-15 20:51 UTC, merged