Fix admin shutdown client issue
NVIDIA/NVFlare pull request #194
Opened 2022-02-09 20:12 UTC by YuanTingHsieh

Fix #193

2022-02-09 20:33 UTC, nvkevlu approved these changes

2022-02-09 20:39 UTC, yhwen requested changes
We need to remove the dead client from admin_server.

2022-02-09 20:39 UTC, yhwen commented on nvflare/private/fed/server/server_engine.py
> -        if self.server.admin_server:
admin_server need to remove the dead client as well. We need this step.

2022-02-09 22:02 UTC, yhwen commented on nvflare/private/fed/server/server_engine.py
> -        if self.server.admin_server:
The root cause of this shutdown issue is the wrong order in the _shutdown_app_on_clients() in the server/training_cmds.py.  The "shutdown" message should be sent to the clients first, then call the engine.remove_clients(). Like below:

        replies = self.send_request_to_clients(conn, message)
        self.process_replies_to_table(conn, replies)

        err = engine.remove_clients(clients)
        if err:
            conn.append_error(err)
            return False

2022-02-10 00:32 UTC, yhwen approved these changes

2022-02-10 01:27 UTC, nvkevlu approved these changes

2022-02-10 01:44 UTC, merged