Update POC tutorials and fix POC bugs
NVIDIA/NVFlare pull request #1958
Opened 2023-08-27 03:26 UTC by chesterxgchen

### Description
* Update the POC tutorial with additional examples of newly added options
* Fix a bug related to the new project_name. The bug was caused that default project_name is always used instead of reflecting the project_name defined in project.yml 

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-08-28 19:50 UTC, nvkevlu commented on examples/tutorials/setup_poc.ipynb
> +    "> If you are the NVFLARE user prior to 2.4.0, you might noticed two things\n",
In my opinion, this is not really a good place to add this extra information. This makes sense in release notes for 2.4, but it becomes excessive in this notebook and will be outdated and not as useful the further we are beyond 2.4.0.

2023-08-28 19:59 UTC, nvkevlu commented on examples/tutorials/setup_poc.ipynb
> +    "> Note: Set NVFLARE_HOME env. variables if only you want to use examples as jobs in POC mode.\n",
I am confused by this, sounds like only you vs other users. Instead, do you mean: Set the NVFLARE_HOME env. variable if you want to use examples as jobs in POC mode.

2023-08-28 19:59 UTC, SYangster requested changes
project_name bug fix looks good, minor cleanup in notebook

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "> * poc command is now separate the sub-commands\n",
suggest "poc command is now separated into sub-commands"

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "> We will need ```tree``` command, so we will install ```tree`` in linux, if tree is not avaialble to you, you can replace it with 'ls -al`"
fix markdown inline code ticks

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "Before running POC mode, there are a few environment variables you might consider to set. These env. variables are consider nice to have but not required since 2.4.0. We have provided other opti
Suggest "Before running POC mode in 2.4.0, there are now a few optional environment variables you might consider to set.

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "We have provided few ways to change the location. Prior to 2.4.0 release, you have to use environment variable. \n",
suggest remove "We have provided few ways to change the location" as it's redundant

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "This should set the default variable to the following location: \n"
What is the following location here?

2023-08-28 19:59 UTC, SYangster commented on examples/tutorials/setup_poc.ipynb
> +    "Now, let's look at the result, if you have ```tree`` command installed in linux (``` pip install tree```), you can use it. otherwise, use ```ls -al```. "
fix markdown inline code ticks

2023-08-28 20:00 UTC, nvkevlu commented on examples/tutorials/setup_poc.ipynb
> +    "Prior 2.4.0 release, the NVFLARE_HOME env. variable is used to find the NVFlare/exampels location. In 2.4.0, we have added \n",
Prior to the 2.4.0 release, the NVFLARE_HOME env. variable was used to find the NVFlare/examples location.

2023-08-28 20:03 UTC, nvkevlu commented on examples/tutorials/setup_poc.ipynb
> +    "Now that we've configured out POC configuration, we can prepare the POC workspace.  By default, the following command will generate POC packages for a server and two clients.\n",
out -> our

2023-08-28 21:27 UTC, SYangster approved these changes

2023-08-28 23:43 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "Once can set the POC_WORKSPACE_DIR as well as other location as well. "
Do you mean "One/We can set the POC_WORKSPACE_DIR to other locations as well."?

2023-08-28 23:54 UTC, YuanTingHsieh commented on nvflare/tool/poc/poc_commands.py
> +    service_commands = _build_commands(cmd_type, poc_workspace, service_config, project_config, excluded, services_list)
if the service_commands is already sorted, do we need the time.sleep(2) in line 804 anymore?

2023-08-28 23:58 UTC, YuanTingHsieh commented on nvflare/tool/poc/poc_commands.py
Is there a better name for this method?
get_all_commands? or get_service_commands?

Another question why does this method start with underscore
But sort_service_cmds does not?

2023-08-28 23:59 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +   "outputs": [],
just to double confirm, so we don't need these usage output here?

2023-08-29 00:00 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "Once can set the POC_WORKSPACE_DIR as well as other location as well. "
Can you elaborate on what are other locations that users can set?

2023-08-29 00:01 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "Before running POC mode in 2.4.0, there are now a few optional environment variables you might consider to set. These env. variables are considered nice to have but not required. We have provide
Agree with Kevin on removing the 2.4.0 VS previous wording here.

2023-08-29 00:28 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "\n",
Maybe remove the "with 2.4.0 upgrade"?

2023-08-29 00:28 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "> If you are the NVFLARE user prior to 2.4.0, you might noticed two things\n",
These two things we could move it to release notes?

2023-08-29 00:31 UTC, YuanTingHsieh commented on examples/tutorials/setup_poc.ipynb
> +    "We can further look at the help description for each command\n",
Do we want to mention these points here?
1. poc command is now separated into sub-commands
2. the sub-commands such as \"prepare\", \"start/stop\" etc. are different from previous version where \"--\" is removed for command

2023-08-29 11:39 UTC, nvkevlu approved these changes

2023-08-30 22:54 UTC, YuanTingHsieh commented
/build

2023-08-30 23:32 UTC, merged