Fix CCWF with FLModelUtil conversion
NVIDIA/NVFlare pull request #2065
Opened 2023-10-08 01:40 UTC by YuanTingHsieh

### Description

If executor is expecting DXO, we should pass DXO instead of raw Shareable

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-10-09 14:37 UTC, yanchengnv requested changes
I don't understand what this PR is for.

2023-10-09 14:37 UTC, yanchengnv commented on nvflare/apis/dxo.py
> +    META = "META"  # only contains meta
In this case, I'd think it should be "NONE" meaning that there is no data.

2023-10-09 14:37 UTC, yanchengnv commented on nvflare/app_common/ccwf/cse_client_ctl.py
> +            dxo = DXO(data_kind=DataKind.META)
I don't see why this is needed.

2023-10-10 18:07 UTC, YuanTingHsieh commented on nvflare/app_common/utils/fl_model_utils.py
fix it here, need to accept "RAW" Shareable, but not just DXO

2023-10-12 14:44 UTC, yanchengnv commented
I don't think we need this PR.

2023-10-12 21:25 UTC, closed without merging

2023-10-12 21:25 UTC, YuanTingHsieh commented
As discussed, we should only pass the shareable header in the case of "cross site evaluation"