Job Cli Upgrade: support custom configurations
NVIDIA/NVFlare pull request #2143
Opened 2023-11-13 23:19 UTC by chesterxgchen

Fixes # .
[FLARE-1624] modify the files in script directory
### Description
This PR addresses the following 3 issues: 
1.  add ".yaml" extension for YAML files.  Yaml file  has both ".yml" and ".yaml" extension. we will map both to omegaconf config format. 
2.  nvflare show_variables -j <job_folder> was broken at some point. This PR fixed this. 
3.  support custom configurations. Allow user specify  -f app/custom/my_config.yaml   k1=v1 format. This will support NeMo type of configuration changes 

The new functionality is explained in Job CLI Tutorials

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2023-11-13 23:28 UTC, IsaacYangSLA commented on examples/advanced/vertical_federated_learning/cifar10-splitnn/set_intersection_file.py
> +        "--config_files",
Plural seems not right.  The default is a single file.

2023-11-13 23:48 UTC, YuanTingHsieh requested changes
Mostly good, some typos

2023-11-13 23:48 UTC, YuanTingHsieh commented on research/one-shot-vfl/set_intersection_file.py
> +        "--config_files",
Why do we need to change this file for JOB CLI?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/fuel/f3/qat/run_server.py
> +        "--config_files", "-f", type=str, help="config file name", required=False, default="net_config.json"
Why do we need to change this file for JOB CLI?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/fuel/f3/qat/run_cell.py
> +        "--config_files", "-f", type=str, help="config file name", required=False, default="net_config.json"
Why do we need to change this file for JOB CLI?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/fuel/f3/qat/admin.py
> +        "--config_files", "-f", type=str, help="config file name", required=False, default="net_config.json"
Why do we need to change this file for JOB CLI?

2023-11-13 23:48 UTC, YuanTingHsieh commented on examples/advanced/vertical_federated_learning/cifar10-splitnn/set_intersection_file.py
> +        "--config_files",
Why do we need to change this file for JOB CLI?

2023-11-13 23:48 UTC, YuanTingHsieh commented on examples/tutorials/job_cli.ipynb
> +    "This impliies that the input config file, is default to \"app1/config/config_client.conf\". Or directly spell out the full path\n",
typo: "implies"

2023-11-13 23:48 UTC, YuanTingHsieh commented on examples/tutorials/job_cli.ipynb
> +    "Let's use an example to demonstrate this with job template \"gpt_nemo\"\n"
job template is called "sag_nemo"

2023-11-13 23:48 UTC, YuanTingHsieh commented on examples/tutorials/job_cli.ipynb
> +    "Notice we use the example script directory \"code\". CLI create job copied the custom folder to the job folder. And there are many custom configuration yaml files. Notice \"weight_decay\" is one
typo: "from 0.01 to 0.02"?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +                    print(f"found cli config for {file=}, {cli_configs=}")
just to confirm, do we want to keep this print?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +        print(f"{app_cli_config_dict=}")
just to confirm, do we want to keep this print?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +            print(f"{config_file=}")
just to confirm, do we want to keep this print?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +            print(f"{config_data=}")
just to confirm, do we want to keep this print?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +            print(f"{app_name=}, {config_file=}, {config_dict=}")
just to confirm, do we want to keep this print?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +def get_config_file_path(app_name, input_file_path, job_folder):
suggest add some test cases for this new method.

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +        # The input_file_path could be in one of the following format
what will happen if users provide an input_file_path starts from the root directory "/hello/cool.conf"?

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/config/configer.py
> +                        app_config_files[app_name] = config_files
What if the custom folder inside it is not flat?
Means there are also folders inside the custom folder.

For example: "custom/cool_dir/something.conf", do we want to support this?
Or we could just say this is not supported.

2023-11-13 23:48 UTC, YuanTingHsieh commented on nvflare/tool/job/job_cli.py
> +        if root != job_folder and (root.endswith("config") or root.endswith("customer")):
typo? should it be `root.endswith("custom")`?

2023-11-13 23:48 UTC, YuanTingHsieh commented on tests/unit_test/tool/job/config/configer_test.py
> +            ["config_fed_client.conf", "app_script=cifar10_fl.py", "launch_once=False"],
good we have a new case without "app",
can we keep the old case that tested both Upper case and Lower case for "false"?

2023-11-13 23:48 UTC, YuanTingHsieh commented on tests/unit_test/tool/job/config/configer_test.py
> +    args.config_file = config_files
one question, do we want the `args.config_file` become `args.config_files`?

2023-11-14 14:51 UTC, YuanTingHsieh commented on tests/unit_test/tool/job/config/configer_test.py
> +        with pytest.raises(ValueError) as excinfo:
It might be better to separate this negative case out

Otherwise it is duplicated for each positive case?

But this is minor

2023-11-14 20:27 UTC, merged