[2.4] Add support to large object to CellPipe
NVIDIA/NVFlare pull request #2401
Opened 2024-03-15 04:39 UTC by YuanTingHsieh

### Description

Add support to large object to CellPipe

- Enable StreamCell for CellPipe's channels
- Update timeout values for larger objects
- Should start the pipe_handler's heartbeat / checking for heartbeat mechanism after the task is pulled and ready to be executed
- MetricRelay component does not need its own heartbeat mechanism

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-03-15 04:39 UTC, YuanTingHsieh commented
/build

2024-03-15 23:59 UTC, SYangster commented on nvflare/app_common/executors/client_api_launcher_executor.py
> +        heartbeat_timeout: float = 60.0,
update default value in docstring

2024-03-15 23:59 UTC, SYangster commented on nvflare/app_common/executors/launcher_executor.py
> +        workers: int = 4,
update default values in docstring

2024-03-18 04:45 UTC, YuanTingHsieh commented
/build

2024-03-18 14:42 UTC, yanchengnv requested changes
Why so many changes? The only change needed is cell.py. 

If you want to improve other things (seem to be non-trivial), please do so in another PR and describe the reason.

2024-03-18 19:16 UTC, YuanTingHsieh commented
Sounds good, the cell changing is moved to https://github.com/NVIDIA/NVFlare/pull/2406 


This PR handles all other issues I encountered in testing large models + LauncherExecutor/Client API

2024-03-18 19:24 UTC, YuanTingHsieh commented
/build

2024-03-19 01:29 UTC, closed without merging