Fix intime accumulate weighted aggregators and add tests
NVIDIA/NVFlare pull request #247
Opened 2022-03-01 22:08 UTC by YuanTingHsieh

Fix #182 

- Added new test cases
- Fixed logic error in `InTimeAccumulateWeightedAggregator`
- Updated docstrings

Let's wait for https://github.com/NVIDIA/NVFlare/pull/237 to be merged then I will put these tests in the correct location.

2022-03-08 23:17 UTC, holgerroth requested changes

2022-03-09 00:07 UTC, YuanTingHsieh commented on test/unit_test/app_common/test_accumulate_weighted_aggregator.py
> +        agg = AccumulateWeightedAggregator(aggregation_weights=aggregation_weights)
Yes, it is mentioned in #183 .
I think it is better to use another PR to do the removal of that.
Since that will affect a few more places.

2022-03-09 01:56 UTC, YuanTingHsieh commented on nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py
> +                "A nested aggregation_weights should specify aggregation_weights for every key in expected_data_kind."
no problem

2022-03-09 01:57 UTC, YuanTingHsieh commented on nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py
> +                            f"exclude_vars[{k}] = {exclude_vars[k]} should be a regex string but get {type(exclude_vars[k])}."
fixed

2022-03-09 15:17 UTC, holgerroth commented on test/unit_test/app_common/test_accumulate_weighted_aggregator.py
> +        agg = AccumulateWeightedAggregator(aggregation_weights=aggregation_weights)
makes sense.

2022-03-09 15:22 UTC, holgerroth approved these changes
Looks good. Nice work.

2022-03-11 00:26 UTC, YuanTingHsieh commented
Move the changes into #288

2022-03-11 00:26 UTC, closed without merging