Data Converter
NVIDIA/NVFlare pull request #2487
Opened 2024-04-10 19:47 UTC by nvidianz

This is the DataConverter implementation for Processor plugin. It's the Python counterpart of 
the C++ plugin.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-04-11 16:15 UTC, yanchengnv requested changes
The logic looks good. See my comments for improvement, mainly in error handling and documentation.

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +        cuts = decoder.decode_int_array()
What's cuts?

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +    def decode_aggregation_context(self, buffer: bytes, fl_ctx: FLContext) -> AggregationContext:
Please document the encoding format of aggr ctx

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +                for row_id in range(self.num_samples):
What if num_samples is not set? Need to handle this exception.

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +            row_ids = decoder.decode_int_array()
What's row_id? Isn't the same as sample_id? If so, let's use the same term.

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +        return AggregationContext(self.features, sample_groups)
The whole method should be in try/except block, since any decode method call could fail.

2024-04-11 16:15 UTC, yanchengnv commented on nvflare/app_common/xgb/sec/processor_data_converter.py
> +    ) -> bytes:
Please document encoding format.

2024-04-17 16:07 UTC, nvidianz commented
Combined in https://github.com/NVIDIA/NVFlare/pull/2512

2024-04-17 16:07 UTC, closed without merging