Local Processor Interface
NVIDIA/NVFlare pull request #2611
Opened 2024-06-04 18:47 UTC by nvidianz

### Description
1. LocalProcessor interface for C++ plugins.
2. Implemented a new mock plugin to test the LocalProcessor interface.
### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-06-04 19:50 UTC, yanchengnv requested changes
Looks good in general. See my comments for improvement.  Main thing is lack of explanation/comments about how the API is to be used/implemented.

2024-06-04 19:50 UTC, yanchengnv commented on integration/xgboost/processor/src/dam/dam.cc
> +    if (size )
Format =>: if (size)

2024-06-04 19:50 UTC, yanchengnv commented on integration/xgboost/processor/src/include/local_processor.h
> +    void Initialize(bool active, std::map<std::string, std::string> params) override;
Please add comments to explain methods of this API.

2024-06-04 19:50 UTC, yanchengnv commented on integration/xgboost/processor/src/include/local_processor.h
> +    void FreeBuffer(void *buffer) override;
Explain what this is and when it is to be called.

2024-06-04 19:50 UTC, yanchengnv commented on integration/xgboost/processor/src/nvflare-plugin/plugin_main.cc
> +processing::Processor *LoadProcessor(char *plugin_name) {
What is this plugin_main used for?

2024-06-04 19:50 UTC, yanchengnv commented on integration/xgboost/processor/src/nvflare-plugin/util.cc
> +std::vector<std::pair<int, int>> distribute_work(size_t num_jobs, size_t num_workers) {
What is it for?

2024-06-05 17:26 UTC, YuanTingHsieh reviewed
Mostly good, one question

2024-06-12 20:30 UTC, nvidianz commented
The change is merged with other PRs.

2024-06-12 20:30 UTC, closed without merging