Ignore TenSeal errors if not secure horizontal training
NVIDIA/NVFlare pull request #2774
Opened 2024-08-08 15:49 UTC by nvidianz

Fixes FLARE-2152.

### Description

1. Ignore Tenseal errors if not horizontal secure training.
2. Fixed a bug in PR #2771 where wrong header is used. The code works but not correct.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-08-08 21:31 UTC, YuanTingHsieh commented
let's wait for #2773 and resolve conflicts after

2024-08-09 00:05 UTC, YuanTingHsieh requested changes

2024-08-09 00:05 UTC, YuanTingHsieh commented on nvflare/app_opt/xgboost/histogram_based_v2/sec/partial_he/util.py
> +        return None, None
I think we don't need this once the conflicts are resolved.

2024-08-09 00:36 UTC, nvidianz commented
PR is based on the wrong version of xgboost. Will do another PR.

2024-08-09 00:36 UTC, closed without merging