Add migration guide
NVIDIA/NVFlare pull request #2806
Opened 2024-08-19 15:17 UTC by nvkevlu

Add migration guide.

### Description

Add migration guide.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-08-21 03:03 UTC, chesterxgchen approved these changes

2024-08-21 22:25 UTC, YuanTingHsieh commented on docs/release_notes/flare_250.rst
> +  - New :class:`SecureDataLoader<nvflare.app_opt.xgboost.histogram_based_v2.secure_data_loader.SecureDataLoader>`
this class is renamed: https://github.com/NVIDIA/NVFlare/blob/main/nvflare/app_opt/xgboost/histogram_based_v2/csv_data_loader.py

2024-08-21 22:25 UTC, YuanTingHsieh commented on docs/release_notes/flare_250.rst
> +
should we mention that all "name" for app_opt need to be changed to the full "path" in config?

2024-08-22 22:22 UTC, chesterxgchen requested changes
@nvkevlu  please update

2024-08-23 00:11 UTC, chesterxgchen reviewed
@nvkevlu  @yhwen  we might need to update the document. need help from Yuhong

2024-08-23 21:25 UTC, yhwen commented on docs/release_notes/flare_250.rst
> +its own app_XXXX job definition, but the Workspace same root folder may result in conflicting model file location.
Added the tree view in docs: https://docs.google.com/document/d/1c0bBYdABiNLNuwZHNtY5OpepOAUj798NS_T2uUugCJc/edit

2024-08-23 21:53 UTC, nvkevlu commented on docs/release_notes/flare_250.rst
> +its own app_XXXX job definition, but the Workspace same root folder may result in conflicting model file location.
added

2024-08-23 22:35 UTC, chesterxgchen approved these changes

2024-08-23 22:57 UTC, merged