Add Flower SuperExec plugin
NVIDIA/NVFlare pull request #2855
Opened 2024-08-27 12:22 UTC by panh99

### Description

This PR adds a FlowerSuperExecPlugin in the new file plugin.py under the nvflare/app_opt/flower/ directory. It enables users to run a Flower app with a Flare backend using the flwr run command, which is the same as how it is done in pure Flower.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-09-04 16:02 UTC, yanchengnv requested changes
Please change to use FlowerJob instead of building the job on your own.

2024-09-04 16:02 UTC, yanchengnv commented on nvflare/app_opt/flower/plugin.py
> +from nvflare import FedJob
No need to import FedJob

2024-09-04 16:02 UTC, yanchengnv commented on nvflare/app_opt/flower/plugin.py
> +from nvflare.app_opt.flower.controller import FlowerController
No need to import FlowerController.

2024-09-04 16:02 UTC, yanchengnv commented on nvflare/app_opt/flower/plugin.py
> +from nvflare.app_opt.flower.executor import FlowerExecutor
No need to import FlowerExecutor.

2024-09-04 16:02 UTC, yanchengnv commented on nvflare/app_opt/flower/plugin.py
> +    return files
Put all located files into a temp folder (e.g. /tmp/nakjsdbwejkbdf), and return this folder path. See comments in below.

2024-09-04 16:34 UTC, panh99 commented on nvflare/app_opt/flower/plugin.py
> +            files = _locate_all_files(Path(fab_path))
Thanks for the comments! We are still planning on the next steps. We will resolve these comments asap after that.

2024-09-09 13:51 UTC, panh99 commented on nvflare/app_opt/flower/plugin.py
> +            job = FlowerJob(job_name, tmp_dir)
Hi @yanchengnv . May I know if this is the correct way to use `FlowerJob`? I somehow got a strange `custom` folder after exporting the Flower job:
![image](https://github.com/user-attachments/assets/28d4a894-f37d-4552-9a7c-4c66163d36a1)

The temporary folder that contains all flower files is correct:
![image](https://github.com/user-attachments/assets/1e2f4d41-2e05-4c84-9c72-756a58c10942)

2024-09-09 19:22 UTC, yanchengnv requested changes
Please pass a "str" as "flower_content" to FlowerJob.

2024-09-09 19:22 UTC, yanchengnv commented on nvflare/app_opt/flower/plugin.py
> +            job = FlowerJob(job_name, tmp_dir)
You cannot directly pass tmp_dir to FlowerJob as "flower_content".
FlowerJob requires the "flower_content" to be a str, whereas tmp_dir is Path.
You need to pass str(tmp_dir) to FlowerJob.

2024-09-10 09:07 UTC, panh99 commented on nvflare/app_opt/flower/plugin.py
> +            job = FlowerJob(job_name, tmp_dir)
@yanchengnv Thanks so much for your help! I've just updated the PR.

2025-02-19 15:32 UTC, yanchengnv commented
No longer need this PR after integrating with latest version of Flower that Flare will submit app to superlink via "flwr run" command.

2025-02-19 15:32 UTC, closed without merging