CC authorizers
NVIDIA/NVFlare pull request #3052
Opened 2024-10-30 19:34 UTC by IsaacYangSLA

### Description

CC authorizers, including ACI (Azure Container Instances w/ skr:2.7 for maa token retrieval), GPU (nvtrust), SNP (AMD), TDX (Intel), Mock (always true).

Rebased to main and tested on Azure ACI.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2024-10-30 19:53 UTC, SYangster commented
Should this PR be for gitlab?

2024-11-15 16:46 UTC, chesterxgchen requested changes
need to make some changes

2024-12-13 23:29 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/aci_authorizer.py
> +                    "http://localhost:8284/attest/maa",
Yes.  The aci is launched with a sidecar which creates an api server.  That server can retrieve maa cc token and replies it on that URL.

2024-12-13 23:29 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/aci_authorizer.py
> +                if count > 5:
OK.  We will make it configurable.

2024-12-13 23:35 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/gpu_authorizer.py
> +    def __init__(self, verifier_url="https://nras.attestation.nvidia.com/v1/attest/gpu", policy_file=None):
I think any caller (or the component configured inside resources.json) can override this verifier_url.  For current release of nvtrust, this URL is the default.

2024-12-13 23:40 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/gpu_authorizer.py
> +GPU_NAMESPACE = "x-nv-gpu"
This is not the policy file.  It's the key for CC manager to route cc tokens to the proper cc authorizer.  MAA tokens would be routed to MAA verifiers.  GPU tokens are routed to GPU verifiers.  The CC manager looks into the keys and delivers the values to the verifiers with the same namespace.

2024-12-13 23:42 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/gpu_authorizer.py
> +        self.client.set_name("nvflare_node")
The nvtrust client requires a name.  We use nvflare_node, but it can be a random string.

2025-01-06 22:28 UTC, IsaacYangSLA commented
/build

2025-01-08 19:30 UTC, IsaacYangSLA commented
/build

2025-01-17 17:52 UTC, chesterxgchen reviewed
asked a few questions

2025-01-17 21:38 UTC, IsaacYangSLA commented on nvflare/app_opt/confidential_computing/gpu_authorizer.py
> +    "x-nvidia-gpu-driver-version":"535.104.05",
Only the dictionary in the "x-nvidia-attestation-detailed-result" is verified.  The driver version is not.  Therefore, different versions are OK.

2025-01-17 21:40 UTC, IsaacYangSLA commented
> asked a few questions

The question about driver-version was answered.

2025-01-22 16:57 UTC, chesterxgchen approved these changes
LGTM

2025-01-22 17:09 UTC, IsaacYangSLA commented
/build

2025-01-22 17:09 UTC, IsaacYangSLA commented
/build

2025-01-22 17:24 UTC, merged