Add commands to list and retrieve additional components
NVIDIA/NVFlare pull request #3114
Opened 2024-12-17 17:15 UTC by nvkevlu

Add commands to list and retrieve additional components.

### Description

After adding additional components to store the error logs (and additional components if implemented in the future), in order to list and download the components, additional admin commands are added.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2025-01-13 17:17 UTC, nvkevlu commented
/build

2025-01-13 18:27 UTC, YuanTingHsieh reviewed
Have some questions regarding user-facing concepts/methods

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/apis/job_def_manager_spec.py
> +        """
What do we mean by "all the client data for the specified job"
Do we mean "all the data coming from all the client sites that associates with this job"?
One example being all the client job logs?

Could we be more specific for the return, by data content do we expect bytes? or a list of names?

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +            list_of_data = job_def_manager.list_client_data(jid=job_id, fl_ctx=fl_ctx)
since it is only used here, do we want to just call the method in job_def_manager  "list_job_components"?

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                ]
Or another way we move these filter mechanism into the "list_client_data" method, so that it does filter out the server-generated data?

One question here is that how do we generate these keys ("meta", "scheduled", "data"), do we have any constant value we can use?

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                    conn.append_string("No client error logs found.")
Should we say "no additional job components from all clients found"? that is a bit unclear as well.
Or "No client data for this job"? But then this error message not matching the method "list_job_components"

I guess we need to define/add some documentation about what do we mean by "job components" and "client data for a job"

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                conn.append_error("internal error", meta=make_meta(MetaStatusValue.INTERNAL_ERROR))
The "download_job" method also has some duplicate codes as this part, maybe we could separate out the common downloading/checking logic to another method and reuse it.

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                ),
do we want download_job_file to be visible? is it still an internal command?

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                    name=AdminCommandNames.LIST_JOB_COMPONENTS,
could this name be just "list_job"?

2025-01-13 18:27 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                    client_cmd=ftd.PULL_FOLDER_FQN,
Instead of a new command, what if we enhance the current "download_job" command to also download all the "components" that belongs to the job?

2025-01-14 17:21 UTC, nvkevlu commented on nvflare/apis/impl/job_def_manager.py
> +        return store.list_components_of_object(self.job_uri(jid))
the reason for this was to list the client logs, but then we made it more generic for data instead of just logs, but you are right, this it not even specific to clients or data, so I will rename it

2025-01-14 17:31 UTC, nvkevlu commented on nvflare/private/fed/server/job_cmds.py
> +                ]
These keys are special since we use them in the system ourselves. For now, I put it into a variable system_components to make it clearer.

2025-01-14 20:54 UTC, yanchengnv requested changes
Looks good in general. See my comments for improvement.

2025-01-14 20:54 UTC, yanchengnv commented on nvflare/apis/impl/job_def_manager.py
> +    def list_components(self, jid: str, fl_ctx: FLContext):
Please add type hint for returned type.

2025-01-14 20:54 UTC, yanchengnv commented on nvflare/private/fed/server/job_cmds.py
> +                ),
It must stay invisible since it is used internally and cannot be issued by the user.

2025-01-14 20:54 UTC, yanchengnv commented on nvflare/private/fed/server/job_cmds.py
> +                    client_cmd=ftd.PULL_FOLDER_FQN,
No, this is because download_job_components may have different permission than download_job.

2025-01-14 20:54 UTC, yanchengnv commented on nvflare/private/fed/server/job_cmds.py
> +                    conn.append_string("No additional job components found.")
Add meta.

2025-01-14 21:17 UTC, nvkevlu commented on nvflare/private/fed/server/job_cmds.py
> +                conn.append_error("internal error", meta=make_meta(MetaStatusValue.INTERNAL_ERROR))
we can clean this up in a future PR

2025-01-14 22:01 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> +                ),
got it, so we should not remove visible=False

2025-01-14 22:09 UTC, yanchengnv requested changes
See my comments to make the meta data easier for programmers to use.

2025-01-14 22:09 UTC, yanchengnv commented on nvflare/private/fed/server/job_cmds.py
> +                        "", meta=make_meta(MetaStatusValue.OK, extra={MetaKey.JOB_COMPONENTS: data_str})
To make the meta content easier for programmers, don't use data_str here (otherwise the programmer will have to parse it). You can directly use filtered_data which is already a parsed list.

2025-01-14 22:40 UTC, YuanTingHsieh commented on nvflare/private/fed/server/job_cmds.py
> -                    visible=False,
we should not remove this line

2025-01-15 12:54 UTC, nvkevlu commented
/build

2025-01-15 15:15 UTC, yanchengnv requested changes
Must keep "visible=False" for download_job_file since this is an internal command and not to be exposed to users.

2025-01-15 15:15 UTC, yanchengnv commented on nvflare/private/fed/server/job_cmds.py
> -                    visible=False,
Yes, must keep visible=False

2025-01-15 16:41 UTC, nvkevlu commented
/build

2025-01-15 22:25 UTC, yanchengnv approved these changes
LGTM

2025-01-16 18:18 UTC, YuanTingHsieh approved these changes

2025-01-16 18:18 UTC, YuanTingHsieh commented
/build

2025-01-16 20:31 UTC, merged