docker job launcher provision
NVIDIA/NVFlare pull request #3116
Opened 2024-12-17 19:23 UTC by yhwen

Fixes # .

### Description

Added docker job launcher configuration provision ability.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2025-01-07 20:07 UTC, yanchengnv requested changes
See comments.

2025-01-07 20:07 UTC, yanchengnv commented on nvflare/lighter/impl/docker.py
> +        communication_port = ctx.get(CtxKey.COMMUNICATION_PORT)
Should get the prop from the server.

2025-01-07 20:07 UTC, yanchengnv commented on nvflare/lighter/impl/static_file.py
> +        communication_port = ctx.get(CtxKey.COMMUNICATION_PORT)
Should get the prop from the server.

2025-01-09 15:37 UTC, yhwen commented on nvflare/lighter/dummy_project.yml
> +    communication_port: 8005
renamed to docker_comm_port.

2025-01-09 15:37 UTC, yhwen commented on nvflare/lighter/dummy_project.yml
> +    communication_port: 8006
renamed to docker_comm_port.

2025-01-09 15:37 UTC, yhwen commented on nvflare/lighter/constants.py
> +    COMMUNICATION_PORT = "communication_port"
renamed to docker_comm_port

2025-01-09 15:38 UTC, yhwen commented on nvflare/lighter/impl/static_file.py
> +        communication_port = ctx.get(CtxKey.COMMUNICATION_PORT)
changed to get_prop from server.

2025-01-09 15:38 UTC, yhwen commented on nvflare/lighter/impl/docker.py
> +        communication_port = ctx.get(CtxKey.COMMUNICATION_PORT)
changed to get_prop from server.

2025-01-09 15:39 UTC, yhwen commented on nvflare/lighter/ctx.py
> +        self[CtxKey.COMMUNICATION_PORT] = server.get_prop(PropKey.COMMUNICATION_PORT, 8005)
no need this, removed.

2025-01-09 18:05 UTC, yanchengnv reviewed
LGTM. @IsaacYangSLA please review.

2025-01-09 18:06 UTC, yanchengnv approved these changes
LGTM

2025-01-13 16:51 UTC, yhwen commented
/build

2025-01-14 20:15 UTC, yanchengnv submitted a review, later dismissed
LGTM

2025-01-14 20:16 UTC, yhwen commented
/build

2025-01-14 21:40 UTC, YuanTingHsieh commented
/build

2025-01-15 08:51 UTC, YuanTingHsieh commented
/build

2025-01-15 15:49 UTC, yhwen commented
/build

2025-01-16 17:43 UTC, YuanTingHsieh commented
/build

2025-01-16 18:19 UTC, YuanTingHsieh commented
/build

2025-01-16 20:06 UTC, YuanTingHsieh commented
/build

2025-01-16 20:43 UTC, YuanTingHsieh submitted a review, later dismissed

2025-01-16 20:43 UTC, YuanTingHsieh commented
/build

2025-01-16 20:59 UTC, YuanTingHsieh approved these changes

2025-01-16 21:14 UTC, merged