Fed Statistics: Adding Percentiles support
NVIDIA/NVFlare pull request #3124
Opened 2024-12-29 05:50 UTC by chesterxgchen

### Description
This is initial work to adding percentile support. Percentiles are very important stats metrics to indicate how many numbers are under certain percentage. 

For example,  p95 (95% percentile) value of user storage = 10 GB,  which means 95 of users are using under 10 GB storage. 
p50 value = median, as it means 50% of values are under this value. This work is going to leverage t-digest. 

This PR includes the followings: 

1. Add percentile support using t-digest
2. Add examples for df_stats
3. refactoring the some of the codebase
4 add job API in examples
5. add percentiles unit tests

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.

2025-01-02 18:33 UTC, yhwen requested changes
Need to update the numeric_stats_test.py because of the API change.

2025-01-02 18:33 UTC, yhwen commented on examples/advanced/federated-statistics/df_stats/job_api/df_statistics.py
> +            "site-2": [0],
Should avoid the hardcode client name "site-1" and "site-2" here. client names can be passed in from the constructor.

2025-01-02 18:33 UTC, yhwen commented on nvflare/app_common/statistics/numeric_stats.py
> +    print(f"\n\n in get_global_stats: {precision=} \n\n")
Should change this to use logger.

2025-01-03 01:17 UTC, SYangster commented on examples/advanced/federated-statistics/df_stats.ipynb
> +    "nvflare simulator df_stats/jobs/df_stats -w /tmp/nvflare/df/workdir -n 2 -t 2\n",
do we need to update the readme accordingly?

2025-01-03 01:30 UTC, SYangster approved these changes
LGTM

2025-01-03 02:15 UTC, yhwen submitted a review, later dismissed

2025-01-03 04:54 UTC, pxLi commented
/build

2025-01-03 04:55 UTC, YanxuanLiu commented
/build

2025-01-03 16:05 UTC, yhwen approved these changes

2025-01-03 16:40 UTC, merged