Update commands
NVIDIA/NVFlare pull request #432
Opened 2022-04-22 21:36 UTC by nvkevlu

- add clone and list jobs to FLAdminAPI
- remove usage of password
- add shutdown system command to set shutdown in overseer

2022-04-22 22:36 UTC, IsaacYangSLA approved these changes
LGTM on the shutdown portion.

2022-04-22 22:47 UTC, YuanTingHsieh commented
Can you run unit tests and integration tests locally and see what's the issue?

2022-04-22 22:54 UTC, YuanTingHsieh requested changes
Let's make sure the unit tests and integration tests are passing

2022-04-25 14:45 UTC, IsaacYangSLA commented
In POC mode, we are using the DummyOverseerAgent, which does not require oversseer to operate.  #406 is to use the actual HttpOverseerAgent.  It may not apply this this case.

2022-04-25 22:59 UTC, YuanTingHsieh approved these changes
Thanks! LGTM, @IsaacYangSLA note that this PR might has minor conflicts with your ongoing PR.

2022-04-25 23:00 UTC, merged