Fix job schedule and deploy with @ALL
NVIDIA/NVFlare pull request #607
Opened 2022-05-25 22:08 UTC by YuanTingHsieh

- Follow up PR for https://github.com/NVIDIA/NVFlare/pull/599

2022-05-25 22:15 UTC, chesterxgchen approved these changes

2022-05-25 22:39 UTC, nvidianz requested changes

2022-05-25 22:39 UTC, nvidianz commented on nvflare/app_common/job_schedulers/job_scheduler.py
> +    if len(all_keys) == 1 and len(deploy_map[all_keys[0]]) == 1 and deploy_map[all_keys[0]][0].upper() == ALL_SITES:
all_keys length is not always 1. For example,

{
  "deploy_map": {
    "app1": ["@ALL"],
    "app2": []
  }
}

2022-05-26 00:46 UTC, nvidianz approved these changes
LGTM

2022-05-26 00:54 UTC, merged