Added proper system shutdown to avoid random Bad file descriptor errors.
NVIDIA/NVFlare pull request #611
Opened 2022-05-26 19:54 UTC by yhwen

Add proper actions to close the ThreadPool when shutdown the system. This is to avoid the random bad file descriptor errors.

2022-05-26 20:11 UTC, chesterxgchen commented on nvflare/private/fed/client/admin_msg_sender.py
> +        self.pool.close()
should you do 
    pool.close()
    pool.join()
https://stackoverflow.com/questions/38271547/when-should-we-call-multiprocessing-pool-join

2022-05-26 20:52 UTC, YuanTingHsieh commented on nvflare/private/fed/server/server_engine.py
>          sys.exit(2)
if we call this sys.exit, will the process just end?

2022-05-26 20:53 UTC, YuanTingHsieh commented on nvflare/private/fed/server/server_engine.py
>          return ""
so we will not get to return here since we call sys.exit in `server_shutdown`?

2022-05-26 21:01 UTC, YuanTingHsieh commented on nvflare/private/fed/server/fed_server.py
> +        self.executor.shutdown()
should have `if self.executor`

2022-05-26 21:02 UTC, YuanTingHsieh requested changes
Thanks for the effort. Minor stuffs as commented

2022-05-27 18:25 UTC, yhwen commented
The sys.exit() only cause the thread to end, not the whole process.

It will still return. Because server_shutdown only cause the other thread to end.

2022-05-27 18:29 UTC, merged