625 Add monai bundle example
NVIDIA/NVFlare pull request #721
Opened 2022-07-22 08:40 UTC by yiheng-wang-nv

This PR is related to #625 , a `hello-monai-bundle` example is added, and the readme file of `hello-monai` is updated.
These two examples are all tested with the latest nvflare 2.1.2

2022-07-22 08:41 UTC, yiheng-wang-nv commented
Hi @YuanTingHsieh , could you please help to check this PR, thanks!
cc @Nic-Ma

2022-07-22 17:53 UTC, YuanTingHsieh commented
/build

2022-07-22 17:58 UTC, YuanTingHsieh commented on examples/hello-monai-bundle/custom/monai_trainer.py
> +# Copyright (c) 2021, NVIDIA CORPORATION.
not sure if this matters, 
can you update to 
```# Copyright (c) 2021-2022, NVIDIA CORPORATION.```

2022-07-22 17:59 UTC, YuanTingHsieh commented on examples/hello-monai-bundle/config/config_fed_server.json
> +    }
can you update this part to

might also want to update the hello-monai example

```

    {
      "id": "aggregator",
      "path": "nvflare.app_common.aggregators.intime_accumulate_model_aggregator.InTimeAccumulateWeightedAggregator",
      "args": {
        "expected_data_kind": "WEIGHTS"
      }
    }

```

2022-07-23 00:36 UTC, YuanTingHsieh commented
@yiheng-wang-nv can you also update both hello-monai examples from "App" structure to "Job" structure?

Basically just adding "meta.json" and introduce a new directory call "app".

You can check similar changes in: https://github.com/NVIDIA/NVFlare/pull/724

2022-07-25 09:04 UTC, yiheng-wang-nv commented
> @yiheng-wang-nv can you also update both hello-monai examples from "App" structure to "Job" structure?
> 
> Basically just adding "meta.json" and introduce a new directory call "app".
> 
> You can check similar changes in: #724

Hi @YuanTingHsieh , I changed but met the following error when type in: `submit_job hello-monai-bundle`
```
Error: No other site can be specified if @ALL is used for job hello-monai-bundle
```
Does the command need to be changed?

2022-07-25 20:19 UTC, YuanTingHsieh commented
> > @yiheng-wang-nv can you also update both hello-monai examples from "App" structure to "Job" structure?
> > Basically just adding "meta.json" and introduce a new directory call "app".
> > You can check similar changes in: #724
> 
> Hi @YuanTingHsieh , I changed but met the following error when type in: `submit_job hello-monai-bundle`
> 
> ```
> Error: No other site can be specified if @ALL is used for job hello-monai-bundle
> ```
> 
> Does the command need to be changed?

Thanks @yiheng-wang-nv for checking.
I made a mistake there.
I have fixed it in that PR.
Can you please check the changes in the PR again and apply it on your PR here?
Thanks

2022-07-26 00:25 UTC, YuanTingHsieh commented
basically the meta.json would be something like:


```
{
  "name": "hello-monai",
  "resource_spec": {},
  "min_clients" : 2,
  "deploy_map": {
    "app": [
      "@ALL"
    ]
  }
}
```

2022-07-26 21:47 UTC, YuanTingHsieh requested changes
code LGTM, can you change the structure to "JOB" like in PR https://github.com/NVIDIA/NVFlare/pull/724

Thanks

2022-07-27 05:15 UTC, yiheng-wang-nv commented
Hi @YuanTingHsieh , thanks! I updated these two examples and tested locally.

2022-07-27 20:06 UTC, YuanTingHsieh commented
/build

2022-07-27 20:54 UTC, YuanTingHsieh approved these changes
Thanks for this PR. LGTM

2022-07-27 20:54 UTC, merged