Add nvflare poc command
NVIDIA/NVFlare pull request #739
Opened 2022-07-29 03:11 UTC by chesterxgchen

nvflare poc -h
usage: nvflare poc [-h] [-n [NUMBER_OF_CLIENTS]] [-w [WORKSPACE]] [-p [PACKAGE]] [--prepare] [--start] [--stop] [--clean]

optional arguments:
  -h, --help            show this help message and exit
  -n [NUMBER_OF_CLIENTS], --number_of_clients [NUMBER_OF_CLIENTS]
                        number of sites or clients
  -w [WORKSPACE], --workspace [WORKSPACE]
                        poc workspace directory
  -p [PACKAGE], --package [PACKAGE]
                        package directory, default to all = all packages, only used for start/stop-poc commands when specified
  --prepare             prepare poc workspace
  --start               start poc
  --stop                stop poc
  --clean               cleanup poc workspace

2022-07-29 08:34 UTC, YuanTingHsieh commented on tests/integration_test/src/admin_controller.py
> +                if ha
accidental removal please undo this change, thanks

2022-07-29 08:47 UTC, YuanTingHsieh commented on nvflare/lighter/nvflare.py
> +    prog_parser, prog_args = parse_args(job_name)
why "job_name" passed in as "prog_name"?

2022-07-29 08:47 UTC, YuanTingHsieh commented on nvflare/lighter/ServiceConstants.py
> +
should the file name be "service_constants.py"?

2022-07-29 08:48 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +        cmd_args.start_poc(cmd_args.workspace, white_list)
should this be just "start_poc(xxx)"?

2022-07-29 08:48 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +        cmd_args.clean_poc(cmd_args.workspace)
should these be changed to calling the functions?

2022-07-29 08:50 UTC, YuanTingHsieh requested changes
Thanks for the PR.
Leave some comments.

And one question here: Why are we changing the "start.sh"/"sub_start.sh" those scripts from permission 755 to 644?

2022-08-01 23:53 UTC, YuanTingHsieh commented on nvflare/lighter/poc.py
> +    return file_dir_path.parent
I personally think this function can be merged with "get_src_poc_dir".
But either way is fine.

2022-08-01 23:54 UTC, YuanTingHsieh commented on nvflare/lighter/poc.py
> +        print(f"Successfully creating poc folder at {dest_poc_folder}.  Please read poc/Readme.rst for user guide.")
@IsaacYangSLA @chesterxgchen does this mean we don't need/pack "poc.zip" anymore?

2022-08-01 23:56 UTC, YuanTingHsieh commented on nvflare/lighter/service_constants.py
> +    DEFAULT_CONSOLE_USER = "admin"
some of the constants are not used, maybe we can remove them.
For example: DEFAULT_CONSOLE_USER

2022-08-02 00:07 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +    )
I personally prefer "packages" instead of "service".
What do you think @IsaacYangSLA @yanchengnv ?

2022-08-02 23:21 UTC, IsaacYangSLA commented on setup.py
>              "poc=nvflare.lighter.poc:main",
We can remove this one (poc=nvflare.lighter.poc:main).

2022-08-02 23:39 UTC, YuanTingHsieh commented on nvflare/lighter/poc.py
> +        exit(1)
From the function name, I think "unpack_poc" should NOT call "copy_from_src".

I think these two functions can be merged inside "clone_poc_folder".

2022-08-02 23:41 UTC, YuanTingHsieh commented on nvflare/lighter/poc.py
> +def prepare_poc(num_clients, poc_workspace):
should we just name this function "genarate_poc"?

2022-08-02 23:43 UTC, YuanTingHsieh commented on nvflare/lighter/service_constants.py
> +    CMD_CLEAN = "clean"
Do we have command "clean"?

2022-08-03 00:00 UTC, YuanTingHsieh commented on nvflare/lighter/poc_commands.py
> +from nvflare.lighter.poc import prepare_poc as generate_poc
@chesterxgchen but you import here as generate_poc

2022-08-03 00:20 UTC, IsaacYangSLA approved these changes
LGTM.

2022-08-03 00:22 UTC, YuanTingHsieh submitted a review, later dismissed
LGTM

2022-08-03 00:22 UTC, YuanTingHsieh commented
/build

2022-08-03 21:18 UTC, IsaacYangSLA commented
/build

2022-08-03 22:07 UTC, IsaacYangSLA approved these changes

2022-08-03 22:22 UTC, merged