add max_bins_percent for histogram
NVIDIA/NVFlare pull request #791
Opened 2022-08-23 03:30 UTC by chesterxgchen

2022-08-23 20:16 UTC, holgerroth requested changes
Additional check is needed. See comment.

2022-08-23 20:16 UTC, holgerroth commented on nvflare/app_common/executors/statistics/statistics_executor.py
> +        if num_of_bins >= item_count * self.max_bins_percent:
There should be a check to ensure that  0.0 <= max_bins_percent <= 1.0

2022-08-24 00:55 UTC, holgerroth submitted a review, later dismissed
LGTM

2022-08-24 02:25 UTC, YuanTingHsieh commented on nvflare/app_common/executors/statistics/statistics_executor.py
> +                raise TypeError(f"{__file__} must implement `Statistics` type. Got: {type(self.stats_generator)}")
Should not be ``__file__``, your file name here is statistics_executor.

2022-08-24 02:26 UTC, YuanTingHsieh reviewed
LGTM, only one minor change needed

2022-08-24 14:39 UTC, yhwen reviewed
Several places in StatisticsExecutor use print() for message logging. Those should be changed to use logger.

2022-08-26 04:56 UTC, closed without merging